#include "phoenix/scripting/invocation_host.hpp"
#include <iostream>
namespace {
phoenix::CanonicalGeometryRef triangle(std::uint64_t offset=0){using namespace phoenix;return CanonicalGeometry::create(
{{{0,0,0},VertexId{1+offset},0},{{1,0,0},VertexId{2+offset},1},{{0,1,0},VertexId{3+offset},2}},
{{0,0,1,2,invalid_geometry_index,invalid_geometry_index,HalfedgeId{10+offset},EdgeId{20+offset},LabelId{31}},{1,0,2,0,invalid_geometry_index,invalid_geometry_index,HalfedgeId{11+offset},EdgeId{21+offset},LabelId{32}},{2,0,0,1,invalid_geometry_index,invalid_geometry_index,HalfedgeId{12+offset},EdgeId{22+offset},LabelId{33}}},{{0,FaceId{40+offset},LabelId{70}}});}
bool exposes_all_inputs(){using namespace phoenix;using namespace phoenix::scripting;ScriptRequest r;r.geometry_inputs={{"left",triangle(),"a"},{"right",triangle(100),"b"}};RunElementIdAllocator ids{1000};InvocationGeometryHost h{31,r,{},&ids};const auto p=h.input_ports();return p.size()==2&&p[0]=="left"&&p[1]=="right"&&h.face_count("right")==1;}
bool publishes_only_explicit_outputs(){using namespace phoenix;using namespace phoenix::scripting;ScriptRequest r;r.geometry_inputs={{"in",triangle(),"a"}};RunElementIdAllocator ids{1100};InvocationGeometryHost h{32,r,{{"out",ScriptOutputKind::geometry},{"unused",ScriptOutputKind::geometry}},&ids};const auto out=h.clone_geometry("in","out");h.create_geometry("unused");ScriptResult result;result.status=EvaluationStatus::completed;result.outputs.push_back({"out",ScriptOutputKind::geometry,{},out,{}});const auto committed=h.finalize(result);return committed.success()&&committed.outputs.size()==1&&committed.outputs[0].geometry.get()==r.geometry_inputs[0].geometry.get();}
bool publishes_stable_element_ids(){using namespace phoenix;using namespace phoenix::scripting;ScriptRequest r;r.geometry_inputs={{"in",triangle(),"a"}};RunElementIdAllocator ids{1200};InvocationGeometryHost h{33,r,{{"mesh",ScriptOutputKind::geometry},{"selected",ScriptOutputKind::faces}},&ids};const auto mesh=h.clone_geometry("in","mesh");const auto faces=h.element_handles(mesh,ScriptOutputKind::faces);ScriptResult result;result.status=EvaluationStatus::completed;result.outputs={{"selected",ScriptOutputKind::faces,{},0,faces},{"mesh",ScriptOutputKind::geometry,{},mesh,{}}};const auto committed=h.finalize(result);return committed.success()&&committed.outputs[0].element_ids==std::vector<std::uint64_t>{40};}
bool rejects_stale_element_outputs(){using namespace phoenix;using namespace phoenix::scripting;ScriptRequest r;r.geometry_inputs={{"in",triangle(),"a"}};RunElementIdAllocator ids{1300};InvocationGeometryHost h{34,r,{{"selected",ScriptOutputKind::faces},{"mesh",ScriptOutputKind::geometry}},&ids};const auto mesh=h.clone_geometry("in","mesh");const auto faces=h.element_handles(mesh,ScriptOutputKind::faces);h.remove_face(mesh,0);ScriptResult result;result.status=EvaluationStatus::completed;result.outputs={{"selected",ScriptOutputKind::faces,{},0,faces}};return !h.finalize(result).success();}
}
int main(){const bool a=exposes_all_inputs(),b=publishes_only_explicit_outputs(),c=publishes_stable_element_ids(),d=rejects_stale_element_outputs();std::cout<<"script host keyed inputs: "<<a<<'\n'<<"script host explicit publication: "<<b<<'\n'<<"script host stable element outputs: "<<c<<'\n'<<"script host stale output rejection: "<<d<<'\n';return a&&b&&c&&d?0:1;}
