#include "phoenix/scripting/invocation_host.hpp"

#include <stdexcept>
#include <type_traits>

namespace phoenix::scripting {
namespace {
template<class T>T value_or_throw(SessionResult<T> value){if(const auto* e=std::get_if<SessionError>(&value))throw std::runtime_error(e->message);return std::get<T>(std::move(value));}
void throw_if(std::optional<SessionError> value){if(value)throw std::runtime_error(value->message);}
Diagnostic diagnostic(std::string message){return {DiagnosticCode::unsupported_result,std::move(message),{}, {}};}
}
InvocationGeometryHost::InvocationGeometryHost(std::uint64_t id,const ScriptRequest& request,
    std::vector<ScriptOutputSpec> outputs,RunElementIdAllocator* ids):session_(id,ids)
{
    for(const auto& item:request.geometry_inputs)if(!inputs_.emplace(item.port,item).second)
        throw std::invalid_argument("Duplicate script input port: "+item.port);
    for(const auto& item:outputs)if(!output_specs_.emplace(item.port,item.kind).second)
        throw std::invalid_argument("Duplicate script output port: "+item.port);
}
std::vector<PortId> InvocationGeometryHost::input_ports() const {std::vector<PortId> r;for(const auto&i:inputs_)r.push_back(i.first);return r;}
const ScriptGeometryInput& InvocationGeometryHost::input(const PortId&p)const{const auto i=inputs_.find(p);if(i==inputs_.end())throw std::out_of_range("Unknown script input port: "+p);return i->second;}
std::size_t InvocationGeometryHost::vertex_count(const PortId&p)const{return input(p).geometry->vertices().size();}
std::size_t InvocationGeometryHost::face_count(const PortId&p)const{return input(p).geometry->faces().size();}
Point3d InvocationGeometryHost::vertex(const PortId&p,std::size_t i)const{return input(p).geometry->vertices().at(i).point;}
ScriptFace InvocationGeometryHost::face(const PortId&p,std::size_t i)const{const auto&g=*input(p).geometry;const auto&f=g.faces().at(i);ScriptFace r;r.label=f.label;auto h=f.halfedge;do{const auto&e=g.halfedges().at(h);r.vertices.push_back(e.origin_vertex);r.directed_edge_labels.push_back(e.label);h=e.next;}while(h!=f.halfedge);return r;}
std::optional<ScriptOutputKind> InvocationGeometryHost::input_selection_kind(const PortId&p)const{return input(p).selection_kind;}
std::vector<std::uint64_t> InvocationGeometryHost::input_selection_handles(const PortId&p){const auto& selected=input(p);if(!selected.selection_kind)return {};auto token=input_geometry_tokens_.find(p);if(token==input_geometry_tokens_.end()){const auto issued=next_token_++;geometries_[issued]=value_or_throw(session_.clone(selected.geometry));input_geometry_tokens_[p]=issued;token=input_geometry_tokens_.find(p);}const auto geometry_handle=geometry(token->second);std::map<std::uint64_t,AnyElement> available;if(*selected.selection_kind==ScriptOutputKind::vertices)for(const auto handle:value_or_throw(session_.vertices(geometry_handle)))available.emplace(value_or_throw(session_.element_id(handle)),handle);else if(*selected.selection_kind==ScriptOutputKind::halfedges)for(const auto handle:value_or_throw(session_.halfedges(geometry_handle)))available.emplace(value_or_throw(session_.element_id(handle)),handle);else if(*selected.selection_kind==ScriptOutputKind::faces)for(const auto handle:value_or_throw(session_.faces(geometry_handle)))available.emplace(value_or_throw(session_.element_id(handle)),handle);else throw std::invalid_argument("Input selection has an invalid element kind.");std::vector<std::uint64_t> result;for(const auto id:selected.selected_element_ids){const auto found=available.find(id);if(found==available.end())throw std::invalid_argument("Input selection references an element absent from its geometry snapshot.");result.push_back(issue(found->second));}return result;}
bool InvocationGeometryHost::output_matches(const PortId&p,ScriptOutputKind k)const{const auto i=output_specs_.find(p);return i!=output_specs_.end()&&i->second==k;}
std::uint64_t InvocationGeometryHost::create_geometry(const PortId&p){if(!output_matches(p,ScriptOutputKind::geometry))throw std::invalid_argument("Undeclared geometry output: "+p);const auto token=next_token_++;geometries_[token]=value_or_throw(session_.create_empty());geometry_outputs_[token]=p;return token;}
std::uint64_t InvocationGeometryHost::clone_geometry(const PortId&i,const PortId&o){if(!output_matches(o,ScriptOutputKind::geometry))throw std::invalid_argument("Undeclared geometry output: "+o);const auto token=next_token_++;geometries_[token]=value_or_throw(session_.clone(input(i).geometry));geometry_outputs_[token]=o;return token;}
GeometryHandle InvocationGeometryHost::geometry(std::uint64_t t)const{const auto i=geometries_.find(t);if(i==geometries_.end())throw std::out_of_range("Unknown script geometry token.");return i->second;}
std::size_t InvocationGeometryHost::geometry_vertex_count(std::uint64_t g)const{return value_or_throw(session_.vertex_count(geometry(g)));}
std::size_t InvocationGeometryHost::geometry_face_count(std::uint64_t g)const{return value_or_throw(session_.face_count(geometry(g)));}
Point3d InvocationGeometryHost::geometry_vertex(std::uint64_t g,std::size_t i)const{return value_or_throw(session_.point(value_or_throw(session_.vertex(geometry(g),static_cast<GeometryIndex>(i)))));}
ScriptFace InvocationGeometryHost::geometry_face(std::uint64_t g,std::size_t i)const{ScriptFace result;const auto face=value_or_throw(session_.face(geometry(g),static_cast<GeometryIndex>(i)));result.label=value_or_throw(session_.label(face));auto halfedge=value_or_throw(session_.halfedge(face));const auto first=halfedge;do{const auto vertex=value_or_throw(session_.source(halfedge));result.vertices.push_back(vertex.index);result.directed_edge_labels.push_back(value_or_throw(session_.label(halfedge)));halfedge=value_or_throw(session_.next(halfedge));}while(halfedge.index!=first.index);return result;}
void InvocationGeometryHost::set_vertex(std::uint64_t g,std::size_t i,Point3d p){throw_if(session_.set_point(value_or_throw(session_.vertex(geometry(g),static_cast<GeometryIndex>(i))),p));}
std::size_t InvocationGeometryHost::add_vertex(std::uint64_t g,Point3d p){return value_or_throw(session_.add_vertex(geometry(g),p)).index;}
void InvocationGeometryHost::set_face_label(std::uint64_t g,std::size_t i,LabelId l){throw_if(session_.set_label(value_or_throw(session_.face(geometry(g),static_cast<GeometryIndex>(i))),l));}
void InvocationGeometryHost::set_directed_edge_label(std::uint64_t g,std::size_t f,std::size_t e,LabelId l){auto h=value_or_throw(session_.halfedge(value_or_throw(session_.face(geometry(g),static_cast<GeometryIndex>(f)))));for(std::size_t i=0;i<e;++i)h=value_or_throw(session_.next(h));throw_if(session_.set_label(h,l));}
void InvocationGeometryHost::add_face(std::uint64_t g,const ScriptFace& f){std::vector<VertexHandle> vertices;for(const auto i:f.vertices)vertices.push_back(value_or_throw(session_.vertex(geometry(g),static_cast<GeometryIndex>(i))));value_or_throw(session_.add_face(geometry(g),vertices,f.label,f.directed_edge_labels));}
void InvocationGeometryHost::remove_face(std::uint64_t g,std::size_t f){const auto face=value_or_throw(session_.face(geometry(g),static_cast<GeometryIndex>(f)));throw_if(session_.erase_facet(value_or_throw(session_.halfedge(face))));}
std::uint64_t InvocationGeometryHost::issue(AnyElement h){const auto token=next_token_++;elements_[token]=std::move(h);return token;}
HalfedgeHandle InvocationGeometryHost::halfedge(std::uint64_t token)const{const auto found=elements_.find(token);if(found==elements_.end()||!std::holds_alternative<HalfedgeHandle>(found->second))throw std::invalid_argument("Expected a script halfedge token.");return std::get<HalfedgeHandle>(found->second);}
std::vector<std::uint64_t> InvocationGeometryHost::element_handles(std::uint64_t g,ScriptOutputKind kind){std::vector<std::uint64_t> result;const auto value=geometry(g);if(kind==ScriptOutputKind::vertices)for(auto h:value_or_throw(session_.vertices(value)))result.push_back(issue(h));else if(kind==ScriptOutputKind::halfedges)for(auto h:value_or_throw(session_.halfedges(value)))result.push_back(issue(h));else if(kind==ScriptOutputKind::faces)for(auto h:value_or_throw(session_.faces(value)))result.push_back(issue(h));else throw std::invalid_argument("Output kind is not an element kind.");return result;}
ScriptMeshInspection InvocationGeometryHost::inspect_geometry(std::uint64_t g){const auto h=geometry(g);ScriptMeshInspection r;r.vertices=value_or_throw(session_.vertex_count(h));r.halfedges=value_or_throw(session_.halfedge_count(h));r.faces=value_or_throw(session_.face_count(h));r.border_halfedges=value_or_throw(session_.border_halfedge_count(h));r.border_edges=value_or_throw(session_.border_edge_count(h));r.empty=value_or_throw(session_.empty(h));r.closed=value_or_throw(session_.is_closed(h));r.pure_bivalent=value_or_throw(session_.is_pure_bivalent(h));r.pure_trivalent=value_or_throw(session_.is_pure_trivalent(h));r.pure_triangle=value_or_throw(session_.is_pure_triangle(h));r.pure_quad=value_or_throw(session_.is_pure_quad(h));return r;}
ScriptElementInspection InvocationGeometryHost::inspect_element(std::uint64_t token){const auto found=elements_.find(token);if(found==elements_.end())throw std::invalid_argument("Unknown script element token.");ScriptElementInspection r;std::visit([&](const auto& h){using T=std::decay_t<decltype(h)>;r.stable_id=value_or_throw(session_.element_id(h));if constexpr(std::is_same_v<T,VertexHandle>){r.kind=ScriptOutputKind::vertices;r.point=value_or_throw(session_.point(h));r.degree=value_or_throw(session_.degree(h));r.bivalent=value_or_throw(session_.is_bivalent(h));r.trivalent=value_or_throw(session_.is_trivalent(h));r.halfedge=issue(value_or_throw(session_.halfedge(h)));for(auto e:value_or_throw(session_.incident_halfedges(h)))r.incident_halfedges.push_back(issue(e));}else if constexpr(std::is_same_v<T,FaceHandle>){r.kind=ScriptOutputKind::faces;r.label=value_or_throw(session_.label(h));r.degree=value_or_throw(session_.degree(h));r.triangle=value_or_throw(session_.is_triangle(h));r.quad=value_or_throw(session_.is_quad(h));r.halfedge=issue(value_or_throw(session_.halfedge(h)));for(auto e:value_or_throw(session_.incident_halfedges(h)))r.incident_halfedges.push_back(issue(e));}else{r.kind=ScriptOutputKind::halfedges;r.label=value_or_throw(session_.label(h));r.degree=value_or_throw(session_.facet_degree(h));r.bivalent=value_or_throw(session_.is_bivalent(h));r.trivalent=value_or_throw(session_.is_trivalent(h));r.triangle=value_or_throw(session_.is_triangle(h));r.quad=value_or_throw(session_.is_quad(h));r.border=value_or_throw(session_.is_border(h));r.border_edge=value_or_throw(session_.is_border_edge(h));r.opposite=issue(value_or_throw(session_.opposite(h)));r.next=issue(value_or_throw(session_.next(h)));r.prev=issue(value_or_throw(session_.prev(h)));r.next_on_vertex=issue(value_or_throw(session_.next_on_vertex(h)));r.prev_on_vertex=issue(value_or_throw(session_.prev_on_vertex(h)));r.source=issue(value_or_throw(session_.source(h)));r.target=issue(value_or_throw(session_.target(h)));const auto f=value_or_throw(session_.face(h));if(f)r.face=issue(*f);for(auto e:value_or_throw(session_.incident_vertex_halfedges(h)))r.incident_halfedges.push_back(issue(e));}},found->second);return r;}
std::uint64_t InvocationGeometryHost::split_edge(std::uint64_t h){return issue(value_or_throw(session_.split_edge(halfedge(h))));}
std::uint64_t InvocationGeometryHost::split_facet(std::uint64_t a,std::uint64_t b){return issue(value_or_throw(session_.split_facet(halfedge(a),halfedge(b))));}
std::uint64_t InvocationGeometryHost::join_facet(std::uint64_t h){return issue(value_or_throw(session_.join_facet(halfedge(h))));}
std::uint64_t InvocationGeometryHost::flip_edge(std::uint64_t h){return issue(value_or_throw(session_.flip_edge(halfedge(h))));}
std::uint64_t InvocationGeometryHost::make_hole(std::uint64_t h){return issue(value_or_throw(session_.make_hole(halfedge(h))));}
std::uint64_t InvocationGeometryHost::fill_hole(std::uint64_t h){return issue(value_or_throw(session_.fill_hole(halfedge(h))));}
std::uint64_t InvocationGeometryHost::split_vertex(std::uint64_t a,std::uint64_t b){return issue(value_or_throw(session_.split_vertex(halfedge(a),halfedge(b))));}
std::uint64_t InvocationGeometryHost::join_vertex(std::uint64_t h){return issue(value_or_throw(session_.join_vertex(halfedge(h))));}
std::uint64_t InvocationGeometryHost::create_center_vertex(std::uint64_t h){return issue(value_or_throw(session_.create_center_vertex(halfedge(h))));}
std::uint64_t InvocationGeometryHost::erase_center_vertex(std::uint64_t h){return issue(value_or_throw(session_.erase_center_vertex(halfedge(h))));}
void InvocationGeometryHost::erase_connected_component(std::uint64_t h){throw_if(session_.erase_connected_component(halfedge(h)));}
std::size_t InvocationGeometryHost::keep_largest_connected_components(std::uint64_t g,std::size_t count){return value_or_throw(session_.keep_largest_connected_components(geometry(g),count));}
void InvocationGeometryHost::clear_geometry(std::uint64_t g){throw_if(session_.clear(geometry(g)));}
void InvocationGeometryHost::inside_out(std::uint64_t g){throw_if(session_.inside_out(geometry(g)));}
void InvocationGeometryHost::normalize_border(std::uint64_t g){throw_if(session_.normalize_border(geometry(g)));}
std::uint64_t InvocationGeometryHost::add_vertex_and_facet_to_border(std::uint64_t a,std::uint64_t b){return issue(value_or_throw(session_.add_vertex_and_facet_to_border(halfedge(a),halfedge(b))));}
std::uint64_t InvocationGeometryHost::add_facet_to_border(std::uint64_t a,std::uint64_t b){return issue(value_or_throw(session_.add_facet_to_border(halfedge(a),halfedge(b))));}
HostCommitResult InvocationGeometryHost::finalize(const ScriptResult& result)
{
    HostCommitResult committed;if(!result.success()){session_.rollback();committed.diagnostics=result.diagnostics;
        if(committed.diagnostics.empty())committed.diagnostics.push_back({DiagnosticCode::evaluation_error,
            "Script execution did not complete.",{}, {}});return committed;}
    std::set<PortId> seen;std::vector<GeometryHandle> geometry_outputs;
    for(const auto&o:result.outputs){if(!seen.insert(o.port).second){committed.diagnostics.push_back(diagnostic("Duplicate script output: "+o.port));break;}if(!output_matches(o.port,o.kind)){committed.diagnostics.push_back(diagnostic("Undeclared or wrongly typed script output: "+o.port));break;}PublishedScriptOutput p;p.port=o.port;p.kind=o.kind;p.scalar=o.scalar;
        if(o.kind==ScriptOutputKind::scalar){if(!o.scalar)committed.diagnostics.push_back(diagnostic("Scalar output has no value: "+o.port));}
        else if(o.kind==ScriptOutputKind::geometry){const auto g=geometries_.find(o.geometry);if(g==geometries_.end()||geometry_outputs_[o.geometry]!=o.port)committed.diagnostics.push_back(diagnostic("Foreign geometry output: "+o.port));else geometry_outputs.push_back(g->second);}
        else {std::set<std::uint64_t> unique;std::optional<GeometryHandle> backing;for(const auto token:o.elements){if(!unique.insert(token).second){committed.diagnostics.push_back(diagnostic("Duplicate element output token."));break;}const auto h=elements_.find(token);if(h==elements_.end()){committed.diagnostics.push_back(diagnostic("Foreign element output token."));break;}try{const auto current=std::visit([](const auto& item){return GeometryHandle{item.session,item.geometry};},h->second);if(backing&&(backing->session!=current.session||backing->geometry!=current.geometry)){committed.diagnostics.push_back(diagnostic("Element output spans multiple geometry objects."));break;}backing=current;if(o.kind==ScriptOutputKind::vertices&&std::holds_alternative<VertexHandle>(h->second))p.element_ids.push_back(value_or_throw(session_.element_id(std::get<VertexHandle>(h->second))));else if(o.kind==ScriptOutputKind::halfedges&&std::holds_alternative<HalfedgeHandle>(h->second))p.element_ids.push_back(value_or_throw(session_.element_id(std::get<HalfedgeHandle>(h->second))));else if(o.kind==ScriptOutputKind::faces&&std::holds_alternative<FaceHandle>(h->second))p.element_ids.push_back(value_or_throw(session_.element_id(std::get<FaceHandle>(h->second))));else committed.diagnostics.push_back(diagnostic("Mixed element output kinds."));}catch(const std::exception&e){committed.diagnostics.push_back(diagnostic(e.what()));break;}}if(backing&&!committed.diagnostics.size())geometry_outputs.push_back(*backing);}
        committed.outputs.push_back(std::move(p));if(!committed.diagnostics.empty())break;}
    if(!committed.diagnostics.empty()){committed.outputs.clear();session_.rollback();return committed;}
    const auto geometries=session_.commit(geometry_outputs);if(!geometries.success()){for(const auto&e:geometries.errors)committed.diagnostics.push_back(diagnostic(e.message));committed.outputs.clear();return committed;}
    std::size_t index=0;for(auto&o:committed.outputs)if(o.kind!=ScriptOutputKind::scalar)o.geometry=geometries.outputs[index++];return committed;
}
} // namespace phoenix::scripting
