#include "phoenix/scripting/quickjs_engine.hpp"
#include "phoenix/scripting/intersections3.hpp"

#include <quickjs.h>

#include <algorithm>
#include <memory>
#include <set>
#include <stdexcept>
#include <type_traits>

namespace phoenix::scripting {
namespace {
struct RuntimeDeleter{void operator()(JSRuntime* p)const noexcept{if(p)JS_FreeRuntime(p);}};
struct ContextDeleter{void operator()(JSContext* p)const noexcept{if(p)JS_FreeContext(p);}};
using Runtime=std::unique_ptr<JSRuntime,RuntimeDeleter>;
using Context=std::unique_ptr<JSContext,ContextDeleter>;
struct InterruptState{const CancellationToken* cancellation=nullptr;std::uint64_t remaining=0;bool cancelled=false;bool exhausted=false;};
int interrupt(JSRuntime*,void* opaque){auto& s=*static_cast<InterruptState*>(opaque);if(s.cancellation&&s.cancellation->cancelled()){s.cancelled=true;return 1;}if(s.remaining==0){s.exhausted=true;return 1;}--s.remaining;return 0;}
JSValue to_js(JSContext* ctx,const Value& value){return std::visit([&](const auto& item)->JSValue{using T=std::decay_t<decltype(item)>;if constexpr(std::is_same_v<T,std::int64_t>)return JS_NewInt64(ctx,item);else if constexpr(std::is_same_v<T,double>)return JS_NewFloat64(ctx,item);else if constexpr(std::is_same_v<T,bool>)return JS_NewBool(ctx,item);else return JS_NewStringLen(ctx,item.data(),item.size());},value);}
std::string text(JSContext* ctx,JSValueConst value){const char* raw=JS_ToCString(ctx,value);if(!raw)return {};std::string result(raw);JS_FreeCString(ctx,raw);return result;}
std::string exception(JSContext* ctx){const auto value=JS_GetException(ctx);auto result=text(ctx,value);JS_FreeValue(ctx,value);return result.empty()?"JavaScript exception.":result;}
EvaluationResult failure(EvaluationStatus status,DiagnosticCode code,std::string message){return {status,{},{{code,std::move(message),{}, {}}}};}
EvaluationResult interrupted(const InterruptState& state){if(state.cancelled)return failure(EvaluationStatus::cancelled,DiagnosticCode::cancelled,"Script evaluation was cancelled.");return failure(EvaluationStatus::budget_exceeded,DiagnosticCode::instruction_budget_exceeded,"Script instruction budget was exceeded.");}
bool set(JSContext* ctx,JSValueConst object,const std::string& name,JSValue value){return JS_SetPropertyStr(ctx,object,name.c_str(),value)>=0;}
std::optional<Value> scalar(JSContext* ctx,JSValueConst value){if(JS_IsBool(value))return Value{JS_ToBool(ctx,value)!=0};if(JS_VALUE_GET_TAG(value)==JS_TAG_INT){std::int64_t result=0;if(JS_ToInt64(ctx,&result,value)<0)return {};return Value{result};}if(JS_IsNumber(value)){double result=0;if(JS_ToFloat64(ctx,&result,value)<0)return {};return Value{result};}if(JS_IsString(value))return Value{text(ctx,value)};return {};}
ScriptResult script_failure(EvaluationStatus status,DiagnosticCode code,std::string message){return {status,{},{{code,std::move(message),{}, {}}},{}};}
ScriptResult script_interrupted(const InterruptState& state){if(state.cancelled)return script_failure(EvaluationStatus::cancelled,DiagnosticCode::cancelled,"Script execution was cancelled.");return script_failure(EvaluationStatus::budget_exceeded,DiagnosticCode::instruction_budget_exceeded,"Script instruction budget was exceeded.");}
struct ScriptContextState{GeometryScriptHost* host=nullptr;std::string console;std::size_t log_entries=0;};
ScriptContextState& script_state(JSContext* ctx){return *static_cast<ScriptContextState*>(JS_GetContextOpaque(ctx));}
GeometryScriptHost& host(JSContext* ctx){return *script_state(ctx).host;}
std::string string_arg(JSContext* ctx,JSValueConst value){const auto result=text(ctx,value);if(result.empty()&&!JS_IsString(value))throw std::invalid_argument("Expected a string argument.");return result;}
std::uint64_t integer_arg(JSContext* ctx,JSValueConst value){std::int64_t result=0;if(JS_ToInt64(ctx,&result,value)<0||result<0)throw std::invalid_argument("Expected a non-negative integer argument.");return static_cast<std::uint64_t>(result);}
double number_arg(JSContext* ctx,JSValueConst value){double result=0;if(JS_ToFloat64(ctx,&result,value)<0)throw std::invalid_argument("Expected a numeric argument.");return result;}
phoenix::LabelId label_arg(JSContext* ctx,JSValueConst value){const auto raw=integer_arg(ctx,value);if(raw>static_cast<std::uint64_t>(INT32_MAX))throw std::invalid_argument("Label identifier is outside the supported integer range.");return phoenix::LabelId{static_cast<std::int32_t>(raw)};}
JSValue native_builder_add_vertex(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_builder_add_face(JSContext*,JSValueConst,int,JSValueConst*);
JSValue handle_object(JSContext* ctx,const char* kind,std::uint64_t token){auto result=JS_NewObject(ctx);if(JS_IsException(result))return result;if(!set(ctx,result,"__phoenixKind",JS_NewString(ctx,kind))||!set(ctx,result,"token",JS_NewInt64(ctx,static_cast<std::int64_t>(token)))){JS_FreeValue(ctx,result);return JS_EXCEPTION;}JS_FreezeObject(ctx,result);return result;}
JSValue builder_object(JSContext* ctx,std::uint64_t token){auto result=JS_NewObject(ctx);set(ctx,result,"__phoenixKind",JS_NewString(ctx,"geometry"));set(ctx,result,"token",JS_NewInt64(ctx,static_cast<std::int64_t>(token)));set(ctx,result,"add_vertex",JS_NewCFunction(ctx,native_builder_add_vertex,"add_vertex",3));set(ctx,result,"add_face",JS_NewCFunction(ctx,native_builder_add_face,"add_face",3));set(ctx,result,"error",JS_NULL);JS_FreezeObject(ctx,result);return result;}
std::uint64_t handle_arg(JSContext* ctx,JSValueConst value){if(!JS_IsObject(value))throw std::invalid_argument("Expected a Phoenix geometry handle.");auto token=JS_GetPropertyStr(ctx,value,"token");const auto result=integer_arg(ctx,token);JS_FreeValue(ctx,token);return result;}
JSValue native_create_geometry(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("createGeometry(output) expects one argument.");return handle_object(ctx,"geometry",host(ctx).create_geometry(string_arg(ctx,argv[0])));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_build_mesh(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("build_mesh(output) expects the explicit geometry output name.");return builder_object(ctx,host(ctx).create_geometry(string_arg(ctx,argv[0])));}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_clone_geometry(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=2)throw std::invalid_argument("cloneGeometry(input, output) expects two arguments.");return handle_object(ctx,"geometry",host(ctx).clone_geometry(string_arg(ctx,argv[0]),string_arg(ctx,argv[1])));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_vertex_count(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("vertexCount(geometry) expects one argument.");return JS_NewInt64(ctx,static_cast<std::int64_t>(host(ctx).geometry_vertex_count(handle_arg(ctx,argv[0]))));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_face_count(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("faceCount(geometry) expects one argument.");return JS_NewInt64(ctx,static_cast<std::int64_t>(host(ctx).geometry_face_count(handle_arg(ctx,argv[0]))));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue point_object(JSContext* ctx,phoenix::Point3d point){auto result=JS_NewObject(ctx);if(JS_IsException(result))return result;if(!set(ctx,result,"x",JS_NewFloat64(ctx,point.x))||!set(ctx,result,"y",JS_NewFloat64(ctx,point.y))||!set(ctx,result,"z",JS_NewFloat64(ctx,point.z))){JS_FreeValue(ctx,result);return JS_EXCEPTION;}JS_FreezeObject(ctx,result);return result;}
JSValue native_vertex(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=2)throw std::invalid_argument("vertex(geometry, index) expects two arguments.");return point_object(ctx,host(ctx).geometry_vertex(handle_arg(ctx,argv[0]),static_cast<std::size_t>(integer_arg(ctx,argv[1]))));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue label_array(JSContext* ctx,const std::vector<phoenix::LabelId>& values){auto result=JS_NewArray(ctx);for(std::size_t i=0;i<values.size();++i)JS_SetPropertyUint32(ctx,result,static_cast<std::uint32_t>(i),JS_NewInt64(ctx,values[i].value()));JS_FreezeObject(ctx,result);return result;}
JSValue index_array(JSContext* ctx,const std::vector<std::uint64_t>& values){auto result=JS_NewArray(ctx);for(std::size_t i=0;i<values.size();++i)JS_SetPropertyUint32(ctx,result,static_cast<std::uint32_t>(i),JS_NewInt64(ctx,static_cast<std::int64_t>(values[i])));JS_FreezeObject(ctx,result);return result;}
JSValue handle_array(JSContext* ctx,const char* kind,const std::vector<std::uint64_t>& values){auto result=JS_NewArray(ctx);for(std::size_t i=0;i<values.size();++i)JS_SetPropertyUint32(ctx,result,static_cast<std::uint32_t>(i),handle_object(ctx,kind,values[i]));JS_FreezeObject(ctx,result);return result;}
JSValue optional_handle(JSContext* ctx,const char* kind,const std::optional<std::uint64_t>& value){return value?handle_object(ctx,kind,*value):JS_NULL;}
JSValue native_inspect_geometry(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("inspectGeometry(mesh) expects one argument.");const auto v=host(ctx).inspect_geometry(handle_arg(ctx,argv[0]));auto r=JS_NewObject(ctx);set(ctx,r,"empty",JS_NewBool(ctx,v.empty));set(ctx,r,"size_of_vertices",JS_NewInt64(ctx,v.vertices));set(ctx,r,"size_of_halfedges",JS_NewInt64(ctx,v.halfedges));set(ctx,r,"size_of_facets",JS_NewInt64(ctx,v.faces));set(ctx,r,"size_of_border_halfedges",JS_NewInt64(ctx,v.border_halfedges));set(ctx,r,"size_of_border_edges",JS_NewInt64(ctx,v.border_edges));set(ctx,r,"is_closed",JS_NewBool(ctx,v.closed));set(ctx,r,"is_pure_bivalent",JS_NewBool(ctx,v.pure_bivalent));set(ctx,r,"is_pure_trivalent",JS_NewBool(ctx,v.pure_trivalent));set(ctx,r,"is_pure_triangle",JS_NewBool(ctx,v.pure_triangle));set(ctx,r,"is_pure_quad",JS_NewBool(ctx,v.pure_quad));JS_FreezeObject(ctx,r);return r;}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_inspect_element(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("inspect(element) expects one argument.");const auto v=host(ctx).inspect_element(handle_arg(ctx,argv[0]));const char* kind=v.kind==ScriptOutputKind::vertices?"vertices":v.kind==ScriptOutputKind::faces?"faces":"halfedges";auto r=JS_NewObject(ctx);set(ctx,r,"kind",JS_NewString(ctx,kind));set(ctx,r,"index",JS_NewInt64(ctx,v.stable_id));set(ctx,r,"degree",JS_NewInt64(ctx,v.degree));set(ctx,r,"is_bivalent",JS_NewBool(ctx,v.bivalent));set(ctx,r,"is_trivalent",JS_NewBool(ctx,v.trivalent));set(ctx,r,"is_triangle",JS_NewBool(ctx,v.triangle));set(ctx,r,"is_quad",JS_NewBool(ctx,v.quad));set(ctx,r,"is_border",JS_NewBool(ctx,v.border));set(ctx,r,"is_border_edge",JS_NewBool(ctx,v.border_edge));if(v.point){set(ctx,r,"point",point_object(ctx,*v.point));set(ctx,r,"x",JS_NewFloat64(ctx,v.point->x));set(ctx,r,"y",JS_NewFloat64(ctx,v.point->y));set(ctx,r,"z",JS_NewFloat64(ctx,v.point->z));}if(v.label)set(ctx,r,"label",JS_NewInt64(ctx,v.label->value()));set(ctx,r,"halfedge",optional_handle(ctx,"halfedges",v.halfedge));set(ctx,r,"opposite",optional_handle(ctx,"halfedges",v.opposite));set(ctx,r,"next",optional_handle(ctx,"halfedges",v.next));set(ctx,r,"prev",optional_handle(ctx,"halfedges",v.prev));set(ctx,r,"next_on_vertex",optional_handle(ctx,"halfedges",v.next_on_vertex));set(ctx,r,"prev_on_vertex",optional_handle(ctx,"halfedges",v.prev_on_vertex));set(ctx,r,"source",optional_handle(ctx,"vertices",v.source));set(ctx,r,"target",optional_handle(ctx,"vertices",v.target));set(ctx,r,"vertex",optional_handle(ctx,"vertices",v.target));set(ctx,r,"facet",optional_handle(ctx,"faces",v.face));set(ctx,r,"incident_halfedges",handle_array(ctx,"halfedges",v.incident_halfedges));JS_FreezeObject(ctx,r);return r;}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_face(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=2)throw std::invalid_argument("face(geometry, index) expects two arguments.");const auto face=host(ctx).geometry_face(handle_arg(ctx,argv[0]),static_cast<std::size_t>(integer_arg(ctx,argv[1])));auto result=JS_NewObject(ctx);if(!set(ctx,result,"vertices",index_array(ctx,face.vertices))||!set(ctx,result,"label",JS_NewInt64(ctx,face.label.value()))||!set(ctx,result,"directedEdgeLabels",label_array(ctx,face.directed_edge_labels))){JS_FreeValue(ctx,result);return JS_EXCEPTION;}JS_FreezeObject(ctx,result);return result;}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_set_vertex(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=5)throw std::invalid_argument("setVertex(geometry, index, x, y, z) expects five arguments.");host(ctx).set_vertex(handle_arg(ctx,argv[0]),static_cast<std::size_t>(integer_arg(ctx,argv[1])),{number_arg(ctx,argv[2]),number_arg(ctx,argv[3]),number_arg(ctx,argv[4])});return JS_UNDEFINED;}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_add_vertex(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=4)throw std::invalid_argument("addVertex(geometry, x, y, z) expects four arguments.");return JS_NewInt64(ctx,static_cast<std::int64_t>(host(ctx).add_vertex(handle_arg(ctx,argv[0]),{number_arg(ctx,argv[1]),number_arg(ctx,argv[2]),number_arg(ctx,argv[3])})));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
std::vector<std::uint64_t> integer_array(JSContext* ctx,JSValueConst value){if(!JS_IsArray(value))throw std::invalid_argument("Expected an array.");std::int64_t count=0;if(JS_GetLength(ctx,value,&count)<0)throw std::invalid_argument("Could not read array length.");std::vector<std::uint64_t> result;for(std::int64_t i=0;i<count;++i){auto item=JS_GetPropertyUint32(ctx,value,static_cast<std::uint32_t>(i));result.push_back(integer_arg(ctx,item));JS_FreeValue(ctx,item);}return result;}
JSValue native_add_face(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc<2||argc>4)throw std::invalid_argument("addFace(geometry, vertices[, label[, edgeLabels]]) expects two to four arguments.");ScriptFace face;face.vertices=integer_array(ctx,argv[1]);if(argc>=3&&!JS_IsUndefined(argv[2]))face.label=label_arg(ctx,argv[2]);if(argc==4){if(!JS_IsArray(argv[3]))throw std::invalid_argument("Directed edge labels must be an array.");std::int64_t count=0;JS_GetLength(ctx,argv[3],&count);for(std::int64_t i=0;i<count;++i){auto item=JS_GetPropertyUint32(ctx,argv[3],static_cast<std::uint32_t>(i));face.directed_edge_labels.push_back(label_arg(ctx,item));JS_FreeValue(ctx,item);}}host(ctx).add_face(handle_arg(ctx,argv[0]),face);return JS_UNDEFINED;}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_builder_add_vertex(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc!=3)throw std::invalid_argument("builder.add_vertex(x, y, z) expects three arguments.");return JS_NewInt64(ctx,static_cast<std::int64_t>(host(ctx).add_vertex(handle_arg(ctx,self),{number_arg(ctx,argv[0]),number_arg(ctx,argv[1]),number_arg(ctx,argv[2])})));}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_builder_add_face(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc<1||argc>3)throw std::invalid_argument("builder.add_face(vertices[, label[, edgeLabels]]) expects one to three arguments.");ScriptFace face;face.vertices=integer_array(ctx,argv[0]);if(argc>=2&&!JS_IsUndefined(argv[1]))face.label=label_arg(ctx,argv[1]);if(argc==3){if(!JS_IsArray(argv[2]))throw std::invalid_argument("Directed edge labels must be an array.");std::int64_t count=0;JS_GetLength(ctx,argv[2],&count);for(std::int64_t i=0;i<count;++i){auto item=JS_GetPropertyUint32(ctx,argv[2],static_cast<std::uint32_t>(i));face.directed_edge_labels.push_back(label_arg(ctx,item));JS_FreeValue(ctx,item);}}host(ctx).add_face(handle_arg(ctx,self),face);return JS_UNDEFINED;}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_set_face_label(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=3)throw std::invalid_argument("setFaceLabel(geometry, face, label) expects three arguments.");host(ctx).set_face_label(handle_arg(ctx,argv[0]),static_cast<std::size_t>(integer_arg(ctx,argv[1])),label_arg(ctx,argv[2]));return JS_UNDEFINED;}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_set_edge_label(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=4)throw std::invalid_argument("setDirectedEdgeLabel(geometry, face, edge, label) expects four arguments.");host(ctx).set_directed_edge_label(handle_arg(ctx,argv[0]),static_cast<std::size_t>(integer_arg(ctx,argv[1])),static_cast<std::size_t>(integer_arg(ctx,argv[2])),label_arg(ctx,argv[3]));return JS_UNDEFINED;}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_remove_face(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=2)throw std::invalid_argument("removeFace(geometry, face) expects two arguments.");host(ctx).remove_face(handle_arg(ctx,argv[0]),static_cast<std::size_t>(integer_arg(ctx,argv[1])));return JS_UNDEFINED;}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_elements(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=2)throw std::invalid_argument("elements(geometry, kind) expects two arguments.");const auto name=string_arg(ctx,argv[1]);const auto kind=name=="vertices"?ScriptOutputKind::vertices:name=="halfedges"?ScriptOutputKind::halfedges:name=="faces"?ScriptOutputKind::faces:throw std::invalid_argument("Element kind must be vertices, halfedges, or faces.");const auto tokens=host(ctx).element_handles(handle_arg(ctx,argv[0]),kind);auto result=JS_NewArray(ctx);for(std::size_t i=0;i<tokens.size();++i)JS_SetPropertyUint32(ctx,result,static_cast<std::uint32_t>(i),handle_object(ctx,name.c_str(),tokens[i]));return result;}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_split_edge(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("splitEdge(halfedge) expects one argument.");return handle_object(ctx,"halfedges",host(ctx).split_edge(handle_arg(ctx,argv[0])));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_split_facet(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=2)throw std::invalid_argument("splitFacet(first, second) expects two arguments.");return handle_object(ctx,"halfedges",host(ctx).split_facet(handle_arg(ctx,argv[0]),handle_arg(ctx,argv[1])));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_join_facet(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("joinFacet(halfedge) expects one argument.");return handle_object(ctx,"halfedges",host(ctx).join_facet(handle_arg(ctx,argv[0])));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_flip_edge(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("flipEdge(halfedge) expects one argument.");return handle_object(ctx,"halfedges",host(ctx).flip_edge(handle_arg(ctx,argv[0])));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_make_hole(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("makeHole(halfedge) expects one argument.");return handle_object(ctx,"halfedges",host(ctx).make_hole(handle_arg(ctx,argv[0])));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_fill_hole(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("fillHole(halfedge) expects one argument.");return handle_object(ctx,"halfedges",host(ctx).fill_hole(handle_arg(ctx,argv[0])));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_split_vertex(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=2)throw std::invalid_argument("splitVertex(first, second) expects two arguments.");return handle_object(ctx,"halfedges",host(ctx).split_vertex(handle_arg(ctx,argv[0]),handle_arg(ctx,argv[1])));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_join_vertex(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("joinVertex(halfedge) expects one argument.");return handle_object(ctx,"halfedges",host(ctx).join_vertex(handle_arg(ctx,argv[0])));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_create_center(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("createCenterVertex(halfedge) expects one argument.");return handle_object(ctx,"halfedges",host(ctx).create_center_vertex(handle_arg(ctx,argv[0])));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_erase_center(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("eraseCenterVertex(halfedge) expects one argument.");return handle_object(ctx,"halfedges",host(ctx).erase_center_vertex(handle_arg(ctx,argv[0])));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_erase_component(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("eraseConnectedComponent(halfedge) expects one argument.");host(ctx).erase_connected_component(handle_arg(ctx,argv[0]));return JS_UNDEFINED;}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_keep_components(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=2)throw std::invalid_argument("keepLargestConnectedComponents(geometry, count) expects two arguments.");return JS_NewInt64(ctx,static_cast<std::int64_t>(host(ctx).keep_largest_connected_components(handle_arg(ctx,argv[0]),static_cast<std::size_t>(integer_arg(ctx,argv[1])))));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_clear(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("clear(geometry) expects one argument.");host(ctx).clear_geometry(handle_arg(ctx,argv[0]));return JS_UNDEFINED;}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_inside_out(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("insideOut(geometry) expects one argument.");host(ctx).inside_out(handle_arg(ctx,argv[0]));return JS_UNDEFINED;}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_normalize_border(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("normalizeBorder(geometry) expects one argument.");host(ctx).normalize_border(handle_arg(ctx,argv[0]));return JS_UNDEFINED;}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_add_vertex_border(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=2)throw std::invalid_argument("addVertexAndFacetToBorder(first, second) expects two arguments.");return handle_object(ctx,"halfedges",host(ctx).add_vertex_and_facet_to_border(handle_arg(ctx,argv[0]),handle_arg(ctx,argv[1])));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_add_facet_border(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=2)throw std::invalid_argument("addFacetToBorder(first, second) expects two arguments.");return handle_object(ctx,"halfedges",host(ctx).add_facet_to_border(handle_arg(ctx,argv[0]),handle_arg(ctx,argv[1])));}catch(const std::exception& e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_log(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){if(argc!=1)return JS_ThrowTypeError(ctx,"log(value) expects one argument.");auto& state=script_state(ctx);const auto value=text(ctx,argv[0]);constexpr std::size_t max_entries=1024,max_bytes=64U<<10U;if(state.log_entries>=max_entries||state.console.size()+value.size()+1>max_bytes)return JS_ThrowRangeError(ctx,"Script console limit exceeded.");state.console+=value;state.console+='\n';++state.log_entries;return JS_UNDEFINED;}
bool add_function(JSContext* ctx,JSValueConst object,const char* name,JSCFunction* function,int arity){return set(ctx,object,name,JS_NewCFunction(ctx,function,name,arity));}
std::optional<std::pair<std::string,std::uint64_t>> decoded_handle(JSContext* ctx,JSValueConst value){if(!JS_IsObject(value))return {};auto kind=JS_GetPropertyStr(ctx,value,"__phoenixKind"),token=JS_GetPropertyStr(ctx,value,"token");if(!JS_IsString(kind)||!JS_IsNumber(token)){JS_FreeValue(ctx,kind);JS_FreeValue(ctx,token);return {};}auto result=std::make_pair(text(ctx,kind),integer_arg(ctx,token));JS_FreeValue(ctx,kind);JS_FreeValue(ctx,token);return result;}
std::string value_kind(JSContext* ctx,JSValueConst value){if(!JS_IsObject(value))throw std::invalid_argument("Expected a Phoenix 3D value.");auto property=JS_GetPropertyStr(ctx,value,"kind");const auto result=text(ctx,property);JS_FreeValue(ctx,property);if(result.empty())throw std::invalid_argument("Expected a tagged Phoenix 3D value.");return result;}
JSValue native_value_transform(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_point_add(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_point_sub(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_vector_add(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_vector_sub(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_vector_mult(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_vector_div(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_has_on(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_opposite(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_projection(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_vertex_at(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_supporting(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_perpendicular(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_plane_side(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_plane_positive(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_plane_negative(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_transform_inverse(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_transform_compose(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_transform_matrix(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_equals(JSContext*,JSValueConst,int,JSValueConst*);
JSValue native_normal(JSContext*,JSValueConst,int,JSValueConst*);
JSValue direction3_object(JSContext*,Direction3d);
double property_number(JSContext* ctx,JSValueConst value,const char* name){auto property=JS_GetPropertyStr(ctx,value,name);const auto result=number_arg(ctx,property);JS_FreeValue(ctx,property);return result;}
Point3d point_value(JSContext* ctx,JSValueConst value){if(value_kind(ctx,value)!="point3")throw std::invalid_argument("Expected point3.");return {property_number(ctx,value,"x"),property_number(ctx,value,"y"),property_number(ctx,value,"z")};}
Vector3d vector_value(JSContext* ctx,JSValueConst value){const auto kind=value_kind(ctx,value);if(kind!="vec3"&&kind!="dir3")throw std::invalid_argument("Expected vec3 or dir3.");return {property_number(ctx,value,"x"),property_number(ctx,value,"y"),property_number(ctx,value,"z")};}
Direction3d direction_value(JSContext* ctx,JSValueConst value){const auto vector=vector_value(ctx,value);const auto result=direction(vector);if(!result)throw std::invalid_argument("Direction cannot be zero or non-finite.");return *result;}
JSValue xyz_object(JSContext* ctx,const char* kind,double x,double y,double z){auto result=JS_NewObject(ctx);if(!set(ctx,result,"kind",JS_NewString(ctx,kind))||!set(ctx,result,"x",JS_NewFloat64(ctx,x))||!set(ctx,result,"y",JS_NewFloat64(ctx,y))||!set(ctx,result,"z",JS_NewFloat64(ctx,z))||!add_function(ctx,result,"transform",native_value_transform,1)){JS_FreeValue(ctx,result);return JS_EXCEPTION;}if(std::string{kind}=="point3"){set(ctx,result,"add",JS_NewCFunction(ctx,native_point_add,"add",1));set(ctx,result,"sub",JS_NewCFunction(ctx,native_point_sub,"sub",1));}else if(std::string{kind}=="vec3"){set(ctx,result,"add",JS_NewCFunction(ctx,native_vector_add,"add",1));set(ctx,result,"sub",JS_NewCFunction(ctx,native_vector_sub,"sub",1));set(ctx,result,"mult",JS_NewCFunction(ctx,native_vector_mult,"mult",1));set(ctx,result,"div",JS_NewCFunction(ctx,native_vector_div,"div",1));if(const auto d=direction(Vector3d{x,y,z}))set(ctx,result,"direction",direction3_object(ctx,*d));}else if(std::string{kind}=="dir3"){set(ctx,result,"dx",JS_NewFloat64(ctx,x));set(ctx,result,"dy",JS_NewFloat64(ctx,y));set(ctx,result,"dz",JS_NewFloat64(ctx,z));auto vector=JS_NewObject(ctx);set(ctx,vector,"kind",JS_NewString(ctx,"vec3"));set(ctx,vector,"x",JS_NewFloat64(ctx,x));set(ctx,vector,"y",JS_NewFloat64(ctx,y));set(ctx,vector,"z",JS_NewFloat64(ctx,z));JS_FreezeObject(ctx,vector);set(ctx,result,"vector",vector);set(ctx,result,"opposite",JS_NewCFunction(ctx,native_opposite,"opposite",0));}JS_FreezeObject(ctx,result);return result;}
JSValue point3_object(JSContext* ctx,Point3d value){return xyz_object(ctx,"point3",value.x,value.y,value.z);}
JSValue direction3_object(JSContext* ctx,Direction3d value){return xyz_object(ctx,"dir3",value.x,value.y,value.z);}
JSValue segment3_object(JSContext* ctx,Segment3d value){auto result=JS_NewObject(ctx);set(ctx,result,"kind",JS_NewString(ctx,"segment3"));set(ctx,result,"source",point3_object(ctx,value.source));set(ctx,result,"target",point3_object(ctx,value.target));set(ctx,result,"min",point3_object(ctx,min(value)));set(ctx,result,"max",point3_object(ctx,max(value)));const auto v=to_vector(value);set(ctx,result,"to_vector",xyz_object(ctx,"vec3",v.x,v.y,v.z));if(const auto d=direction(value))set(ctx,result,"direction",direction3_object(ctx,*d));set(ctx,result,"squared_length",JS_NewFloat64(ctx,squared_length(value)));set(ctx,result,"is_degenerate",JS_NewBool(ctx,is_degenerate(value)));add_function(ctx,result,"vertex",native_vertex_at,1);add_function(ctx,result,"supporting_line",native_supporting,0);add_function(ctx,result,"has_on",native_has_on,1);add_function(ctx,result,"opposite",native_opposite,0);add_function(ctx,result,"transform",native_value_transform,1);JS_FreezeObject(ctx,result);return result;}
JSValue line3_object(JSContext* ctx,Line3d value){auto result=JS_NewObject(ctx);set(ctx,result,"kind",JS_NewString(ctx,"line3"));set(ctx,result,"point",point3_object(ctx,value.point));set(ctx,result,"direction",direction3_object(ctx,value.direction));const auto v=to_vector(value);set(ctx,result,"to_vector",xyz_object(ctx,"vec3",v.x,v.y,v.z));set(ctx,result,"is_degenerate",JS_NewBool(ctx,false));add_function(ctx,result,"projection",native_projection,1);add_function(ctx,result,"perpendicular_plane",native_perpendicular,1);add_function(ctx,result,"has_on",native_has_on,1);add_function(ctx,result,"opposite",native_opposite,0);add_function(ctx,result,"transform",native_value_transform,1);JS_FreezeObject(ctx,result);return result;}
JSValue plane3_object(JSContext* ctx,Plane3d value){auto result=JS_NewObject(ctx);set(ctx,result,"kind",JS_NewString(ctx,"plane3"));set(ctx,result,"a",JS_NewFloat64(ctx,value.a));set(ctx,result,"b",JS_NewFloat64(ctx,value.b));set(ctx,result,"c",JS_NewFloat64(ctx,value.c));set(ctx,result,"d",JS_NewFloat64(ctx,value.d));set(ctx,result,"point",point3_object(ctx,point(value)));const auto n=orthogonal_vector(value),u=base1(value),v=base2(value);set(ctx,result,"orthogonal_vector",xyz_object(ctx,"vec3",n.x,n.y,n.z));if(const auto direction=orthogonal_direction(value))set(ctx,result,"orthogonal_direction",direction3_object(ctx,*direction));set(ctx,result,"base1",xyz_object(ctx,"vec3",u.x,u.y,u.z));set(ctx,result,"base2",xyz_object(ctx,"vec3",v.x,v.y,v.z));set(ctx,result,"is_degenerate",JS_NewBool(ctx,is_degenerate(value)));add_function(ctx,result,"projection",native_projection,1);add_function(ctx,result,"perpendicular_line",native_perpendicular,1);add_function(ctx,result,"oriented_side",native_plane_side,1);add_function(ctx,result,"has_on_positive_side",native_plane_positive,1);add_function(ctx,result,"has_on_negative_side",native_plane_negative,1);add_function(ctx,result,"has_on",native_has_on,1);add_function(ctx,result,"opposite",native_opposite,0);add_function(ctx,result,"transform",native_value_transform,1);JS_FreezeObject(ctx,result);return result;}
Segment3d segment_value(JSContext* ctx,JSValueConst value){if(value_kind(ctx,value)!="segment3")throw std::invalid_argument("Expected segment3.");auto source=JS_GetPropertyStr(ctx,value,"source"),target=JS_GetPropertyStr(ctx,value,"target");const auto result=Segment3d{point_value(ctx,source),point_value(ctx,target)};JS_FreeValue(ctx,source);JS_FreeValue(ctx,target);return result;}
Line3d line_value(JSContext* ctx,JSValueConst value){if(value_kind(ctx,value)!="line3")throw std::invalid_argument("Expected line3.");auto point=JS_GetPropertyStr(ctx,value,"point"),direction=JS_GetPropertyStr(ctx,value,"direction");const auto result=Line3d{point_value(ctx,point),direction_value(ctx,direction)};JS_FreeValue(ctx,point);JS_FreeValue(ctx,direction);return result;}
Plane3d plane_value(JSContext* ctx,JSValueConst value){if(value_kind(ctx,value)!="plane3")throw std::invalid_argument("Expected plane3.");return {property_number(ctx,value,"a"),property_number(ctx,value,"b"),property_number(ctx,value,"c"),property_number(ctx,value,"d")};}
Ray3d ray_value(JSContext* ctx,JSValueConst value){if(value_kind(ctx,value)!="ray3")throw std::invalid_argument("Expected ray3.");auto source=JS_GetPropertyStr(ctx,value,"source"),direction=JS_GetPropertyStr(ctx,value,"direction");const auto result=Ray3d{point_value(ctx,source),direction_value(ctx,direction)};JS_FreeValue(ctx,source);JS_FreeValue(ctx,direction);return result;}
Triangle3d triangle_value(JSContext* ctx,JSValueConst value){if(value_kind(ctx,value)!="triangle3")throw std::invalid_argument("Expected triangle3.");Triangle3d result;for(std::uint32_t i=0;i<3;++i){auto vertex=JS_GetPropertyUint32(ctx,value,i);result.vertices[i]=point_value(ctx,vertex);JS_FreeValue(ctx,vertex);}return result;}
Transform3d transform_value(JSContext* ctx,JSValueConst value){if(value_kind(ctx,value)!="transform3")throw std::invalid_argument("Expected transform3.");auto matrix=JS_GetPropertyStr(ctx,value,"matrix");if(!JS_IsArray(matrix)){JS_FreeValue(ctx,matrix);throw std::invalid_argument("Transform matrix is invalid.");}Transform3d result;for(std::uint32_t i=0;i<16;++i){auto item=JS_GetPropertyUint32(ctx,matrix,i);result.matrix[i]=number_arg(ctx,item);JS_FreeValue(ctx,item);}JS_FreeValue(ctx,matrix);return result;}
JSValue ray3_object(JSContext* ctx,Ray3d value){auto result=JS_NewObject(ctx);set(ctx,result,"kind",JS_NewString(ctx,"ray3"));set(ctx,result,"source",point3_object(ctx,value.source));set(ctx,result,"direction",direction3_object(ctx,value.direction));const Vector3d v{value.direction.x,value.direction.y,value.direction.z};set(ctx,result,"to_vector",xyz_object(ctx,"vec3",v.x,v.y,v.z));set(ctx,result,"is_degenerate",JS_NewBool(ctx,false));add_function(ctx,result,"supporting_line",native_supporting,0);add_function(ctx,result,"has_on",native_has_on,1);add_function(ctx,result,"opposite",native_opposite,0);add_function(ctx,result,"transform",native_value_transform,1);JS_FreezeObject(ctx,result);return result;}
JSValue triangle3_object(JSContext* ctx,Triangle3d value){auto result=JS_NewArray(ctx);set(ctx,result,"kind",JS_NewString(ctx,"triangle3"));for(std::uint32_t i=0;i<3;++i)JS_SetPropertyUint32(ctx,result,i,point3_object(ctx,value.vertices[i]));set(ctx,result,"squared_area",JS_NewFloat64(ctx,squared_area(value)));set(ctx,result,"is_degenerate",JS_NewBool(ctx,is_degenerate(value)));add_function(ctx,result,"vertex",native_vertex_at,1);add_function(ctx,result,"supporting_plane",native_supporting,0);add_function(ctx,result,"has_on",native_has_on,1);add_function(ctx,result,"transform",native_value_transform,1);JS_FreezeObject(ctx,result);return result;}
JSValue transform3_object(JSContext* ctx,const Transform3d& value){auto result=JS_NewObject(ctx),matrix=JS_NewArray(ctx);for(std::uint32_t i=0;i<16;++i)JS_SetPropertyUint32(ctx,matrix,i,JS_NewFloat64(ctx,value.matrix[i]));JS_FreezeObject(ctx,matrix);set(ctx,result,"kind",JS_NewString(ctx,"transform3"));set(ctx,result,"matrix",matrix);set(ctx,result,"is_even",JS_NewBool(ctx,is_even(value)));set(ctx,result,"is_odd",JS_NewBool(ctx,!is_even(value)));add_function(ctx,result,"m",native_transform_matrix,2);add_function(ctx,result,"inverse",native_transform_inverse,0);add_function(ctx,result,"transform",native_transform_compose,1);JS_FreezeObject(ctx,result);return result;}
JSValue native_point3(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=3)throw std::invalid_argument("point3(x, y, z) expects three arguments.");const Point3d value{number_arg(ctx,argv[0]),number_arg(ctx,argv[1]),number_arg(ctx,argv[2])};if(!finite(value))throw std::invalid_argument("point3 coordinates must be finite.");return point3_object(ctx,value);}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_vec3(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=3)throw std::invalid_argument("vec3(x, y, z) expects three arguments.");const Vector3d value{number_arg(ctx,argv[0]),number_arg(ctx,argv[1]),number_arg(ctx,argv[2])};if(!finite(value))throw std::invalid_argument("vec3 coordinates must be finite.");return xyz_object(ctx,"vec3",value.x,value.y,value.z);}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_dir3(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=3)throw std::invalid_argument("dir3(x, y, z) expects three arguments.");const auto value=direction(Vector3d{number_arg(ctx,argv[0]),number_arg(ctx,argv[1]),number_arg(ctx,argv[2])});if(!value)throw std::invalid_argument("dir3 cannot be zero or non-finite.");return direction3_object(ctx,*value);}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_segment3(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=2)throw std::invalid_argument("segment3(source, target) expects two arguments.");return segment3_object(ctx,{point_value(ctx,argv[0]),point_value(ctx,argv[1])});}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_line3(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=2)throw std::invalid_argument("line3(point, direction) expects two arguments.");return line3_object(ctx,{point_value(ctx,argv[0]),direction_value(ctx,argv[1])});}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_plane3(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=4)throw std::invalid_argument("plane3(a, b, c, d) expects four arguments.");const Plane3d value{number_arg(ctx,argv[0]),number_arg(ctx,argv[1]),number_arg(ctx,argv[2]),number_arg(ctx,argv[3])};if(is_degenerate(value))throw std::invalid_argument("plane3 normal cannot be zero.");return plane3_object(ctx,value);}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_ray3(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=2)throw std::invalid_argument("ray3(source, direction) expects two arguments.");return ray3_object(ctx,{point_value(ctx,argv[0]),direction_value(ctx,argv[1])});}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_triangle3(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=3)throw std::invalid_argument("triangle3(a, b, c) expects three arguments.");return triangle3_object(ctx,{{point_value(ctx,argv[0]),point_value(ctx,argv[1]),point_value(ctx,argv[2])}});}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_transform3(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1||!JS_IsArray(argv[0]))throw std::invalid_argument("transform3(matrix) expects a 16-value array.");std::int64_t count=0;JS_GetLength(ctx,argv[0],&count);if(count!=16)throw std::invalid_argument("transform3 matrix must contain 16 values.");Transform3d value;for(std::uint32_t i=0;i<16;++i){auto item=JS_GetPropertyUint32(ctx,argv[0],i);value.matrix[i]=number_arg(ctx,item);JS_FreeValue(ctx,item);}return transform3_object(ctx,value);}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_identity(JSContext* ctx,JSValueConst,int argc,JSValueConst*){if(argc)return JS_ThrowTypeError(ctx,"identity() expects no arguments.");return transform3_object(ctx,Transform3d::identity());}
JSValue native_translation(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("translation(vector) expects one argument.");return transform3_object(ctx,Transform3d::translation(vector_value(ctx,argv[0])));}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_scaling(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=3)throw std::invalid_argument("scaling(x, y, z) expects three arguments.");return transform3_object(ctx,Transform3d::scaling(number_arg(ctx,argv[0]),number_arg(ctx,argv[1]),number_arg(ctx,argv[2])));}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_rotation(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=2)throw std::invalid_argument("rotation(axis, radians) expects two arguments.");return transform3_object(ctx,Transform3d::rotation(direction_value(ctx,argv[0]),number_arg(ctx,argv[1])));}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue intersection_object(JSContext* ctx,const Intersection3& value){return std::visit([&](const auto& item)->JSValue{using T=std::decay_t<decltype(item)>;if constexpr(std::is_same_v<T,std::monostate>)return JS_NULL;else if constexpr(std::is_same_v<T,Point3d>)return point3_object(ctx,item);else if constexpr(std::is_same_v<T,Line3d>)return line3_object(ctx,item);else if constexpr(std::is_same_v<T,Segment3d>)return segment3_object(ctx,item);else return plane3_object(ctx,item);},value);}
JSValue native_intersection(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=2)throw std::invalid_argument("intersection(left, right) expects two arguments.");const auto a=value_kind(ctx,argv[0]),b=value_kind(ctx,argv[1]);if(a=="line3"&&b=="line3")return intersection_object(ctx,intersection(line_value(ctx,argv[0]),line_value(ctx,argv[1])));if(a=="line3"&&b=="plane3")return intersection_object(ctx,intersection(line_value(ctx,argv[0]),plane_value(ctx,argv[1])));if(a=="plane3"&&b=="line3")return intersection_object(ctx,intersection(plane_value(ctx,argv[0]),line_value(ctx,argv[1])));if(a=="line3"&&b=="segment3")return intersection_object(ctx,intersection(line_value(ctx,argv[0]),segment_value(ctx,argv[1])));if(a=="segment3"&&b=="line3")return intersection_object(ctx,intersection(segment_value(ctx,argv[0]),line_value(ctx,argv[1])));if(a=="plane3"&&b=="plane3")return intersection_object(ctx,intersection(plane_value(ctx,argv[0]),plane_value(ctx,argv[1])));if(a=="plane3"&&b=="segment3")return intersection_object(ctx,intersection(plane_value(ctx,argv[0]),segment_value(ctx,argv[1])));if(a=="segment3"&&b=="plane3")return intersection_object(ctx,intersection(segment_value(ctx,argv[0]),plane_value(ctx,argv[1])));if(a=="segment3"&&b=="segment3")return intersection_object(ctx,intersection(segment_value(ctx,argv[0]),segment_value(ctx,argv[1])));throw std::invalid_argument("Unsupported 3D intersection pair.");}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_point_add(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("point.add(vector) expects one argument.");return point3_object(ctx,add(point_value(ctx,self),vector_value(ctx,argv[0])));}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_point_sub(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("point.sub(vector) expects one argument.");return point3_object(ctx,subtract(point_value(ctx,self),vector_value(ctx,argv[0])));}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_vector_add(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("vector.add(vector) expects one argument.");const auto value=add(vector_value(ctx,self),vector_value(ctx,argv[0]));return xyz_object(ctx,"vec3",value.x,value.y,value.z);}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_vector_sub(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("vector.sub(vector) expects one argument.");const auto value=subtract(vector_value(ctx,self),vector_value(ctx,argv[0]));return xyz_object(ctx,"vec3",value.x,value.y,value.z);}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_vector_mult(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("vector.mult(scalar) expects one argument.");const auto value=multiply(vector_value(ctx,self),number_arg(ctx,argv[0]));return xyz_object(ctx,"vec3",value.x,value.y,value.z);}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_vector_div(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("vector.div(scalar) expects one argument.");const auto divisor=number_arg(ctx,argv[0]);if(divisor==0)throw std::invalid_argument("Cannot divide a vector by zero.");const auto value=divide(vector_value(ctx,self),divisor);return xyz_object(ctx,"vec3",value.x,value.y,value.z);}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_has_on(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("has_on(point) expects one argument.");const auto point=point_value(ctx,argv[0]);const auto kind=value_kind(ctx,self);if(kind=="segment3")return JS_NewBool(ctx,has_on(segment_value(ctx,self),point));if(kind=="line3")return JS_NewBool(ctx,has_on(line_value(ctx,self),point));if(kind=="ray3")return JS_NewBool(ctx,has_on(ray_value(ctx,self),point));if(kind=="triangle3")return JS_NewBool(ctx,has_on(triangle_value(ctx,self),point));if(kind=="plane3")return JS_NewBool(ctx,has_on(plane_value(ctx,self),point));throw std::invalid_argument("Value does not support has_on.");}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_opposite(JSContext* ctx,JSValueConst self,int argc,JSValueConst*){try{if(argc)throw std::invalid_argument("opposite() expects no arguments.");const auto kind=value_kind(ctx,self);if(kind=="segment3")return segment3_object(ctx,opposite(segment_value(ctx,self)));if(kind=="line3")return line3_object(ctx,opposite(line_value(ctx,self)));if(kind=="ray3")return ray3_object(ctx,opposite(ray_value(ctx,self)));if(kind=="plane3")return plane3_object(ctx,opposite(plane_value(ctx,self)));if(kind=="dir3")return direction3_object(ctx,opposite(direction_value(ctx,self)));throw std::invalid_argument("Value does not support opposite.");}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_value_transform(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("transform(value) expects one argument.");const auto matrix=transform_value(ctx,argv[0]);const auto kind=value_kind(ctx,self);if(kind=="point3")return point3_object(ctx,transform(point_value(ctx,self),matrix));if(kind=="vec3"){const auto value=transform(vector_value(ctx,self),matrix);return xyz_object(ctx,"vec3",value.x,value.y,value.z);}if(kind=="dir3")return direction3_object(ctx,transform(direction_value(ctx,self),matrix));if(kind=="segment3")return segment3_object(ctx,transform(segment_value(ctx,self),matrix));if(kind=="line3")return line3_object(ctx,transform(line_value(ctx,self),matrix));if(kind=="ray3")return ray3_object(ctx,transform(ray_value(ctx,self),matrix));if(kind=="triangle3")return triangle3_object(ctx,transform(triangle_value(ctx,self),matrix));if(kind=="plane3")return plane3_object(ctx,transform(plane_value(ctx,self),matrix));throw std::invalid_argument("Value does not support transform.");}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_projection(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("projection(point) expects one argument.");const auto p=point_value(ctx,argv[0]);const auto kind=value_kind(ctx,self);if(kind=="line3")return point3_object(ctx,projection(line_value(ctx,self),p));if(kind=="plane3")return point3_object(ctx,projection(plane_value(ctx,self),p));throw std::invalid_argument("Value does not support projection.");}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_vertex_at(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("vertex(index) expects one argument.");const auto index=static_cast<std::size_t>(integer_arg(ctx,argv[0]));const auto kind=value_kind(ctx,self);const auto result=kind=="segment3"?vertex(segment_value(ctx,self),index):kind=="triangle3"?vertex(triangle_value(ctx,self),index):std::optional<Point3d>{};if(!result)throw std::out_of_range("Primitive vertex index is out of range.");return point3_object(ctx,*result);}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_supporting(JSContext* ctx,JSValueConst self,int argc,JSValueConst*){try{if(argc)throw std::invalid_argument("Supporting primitive method expects no arguments.");const auto kind=value_kind(ctx,self);if(kind=="segment3")return line3_object(ctx,supporting_line(segment_value(ctx,self)));if(kind=="ray3")return line3_object(ctx,supporting_line(ray_value(ctx,self)));if(kind=="triangle3")return plane3_object(ctx,supporting_plane(triangle_value(ctx,self)));throw std::invalid_argument("Value has no supporting primitive.");}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_perpendicular(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("Perpendicular construction expects one point.");const auto p=point_value(ctx,argv[0]);const auto kind=value_kind(ctx,self);if(kind=="line3")return plane3_object(ctx,perpendicular_plane(line_value(ctx,self),p));if(kind=="plane3")return line3_object(ctx,perpendicular_line(plane_value(ctx,self),p));throw std::invalid_argument("Value has no perpendicular construction.");}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_plane_side(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("oriented_side(point) expects one argument.");return JS_NewInt32(ctx,oriented_side(plane_value(ctx,self),point_value(ctx,argv[0])));}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_plane_positive(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("has_on_positive_side(point) expects one argument.");return JS_NewBool(ctx,oriented_side(plane_value(ctx,self),point_value(ctx,argv[0]))>0);}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_plane_negative(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("has_on_negative_side(point) expects one argument.");return JS_NewBool(ctx,oriented_side(plane_value(ctx,self),point_value(ctx,argv[0]))<0);}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_transform_inverse(JSContext* ctx,JSValueConst self,int argc,JSValueConst*){try{if(argc)throw std::invalid_argument("inverse() expects no arguments.");const auto result=inverse(transform_value(ctx,self));if(!result)throw std::invalid_argument("Transform is singular.");return transform3_object(ctx,*result);}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_transform_compose(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc!=1)throw std::invalid_argument("transform(other) expects one argument.");return transform3_object(ctx,compose(transform_value(ctx,self),transform_value(ctx,argv[0])));}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_transform_matrix(JSContext* ctx,JSValueConst self,int argc,JSValueConst* argv){try{if(argc!=2)throw std::invalid_argument("m(row, column) expects two arguments.");const auto row=integer_arg(ctx,argv[0]),column=integer_arg(ctx,argv[1]);if(row>3||column>3)throw std::out_of_range("Transform matrix index is out of range.");return JS_NewFloat64(ctx,transform_value(ctx,self).matrix[row*4+column]);}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_equals(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{if(argc!=2)throw std::invalid_argument("equals(left, right) expects two arguments.");return JS_NewBool(ctx,number_arg(ctx,argv[0])==number_arg(ctx,argv[1]));}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
JSValue native_normal(JSContext* ctx,JSValueConst,int argc,JSValueConst* argv){try{Triangle3d triangle;if(argc==1)triangle=triangle_value(ctx,argv[0]);else if(argc==3)triangle={{point_value(ctx,argv[0]),point_value(ctx,argv[1]),point_value(ctx,argv[2])}};else throw std::invalid_argument("normal(triangle) or normal(a, b, c) expected.");const auto value=direction(cross(vector(triangle.vertices[0],triangle.vertices[1]),vector(triangle.vertices[0],triangle.vertices[2])));if(!value)return JS_NULL;return direction3_object(ctx,*value);}catch(const std::exception&e){return JS_ThrowTypeError(ctx,"%s",e.what());}}
}
std::string QuickJsEngine::engine_id()const{return "quickjs-ng";}
std::string QuickJsEngine::engine_version()const{return std::to_string(QJS_VERSION_MAJOR)+"."+std::to_string(QJS_VERSION_MINOR)+"."+std::to_string(QJS_VERSION_PATCH);}
EvaluationResult QuickJsEngine::evaluate(const EvaluationRequest& request,const CancellationToken* cancellation)const
{
    const auto validated=validate_request(request);if(!validated.success())return {EvaluationStatus::rejected,{},validated.diagnostics};
    if(cancellation&&cancellation->cancelled())return failure(EvaluationStatus::cancelled,DiagnosticCode::cancelled,"Script evaluation was cancelled.");
    Runtime runtime{JS_NewRuntime()};if(!runtime)return failure(EvaluationStatus::failed,DiagnosticCode::engine_unavailable,"QuickJS runtime allocation failed.");
    JS_SetMemoryLimit(runtime.get(),static_cast<std::size_t>(request.limits.memory_bytes));
    const auto stack=std::max<std::uint64_t>(64U<<10U,std::min<std::uint64_t>(request.limits.memory_bytes/4,static_cast<std::uint64_t>(request.limits.recursion_depth)*(16U<<10U)));
    JS_SetMaxStackSize(runtime.get(),static_cast<std::size_t>(stack));
    InterruptState state{cancellation,std::max<std::uint64_t>(1,request.limits.instruction_budget/1024),false,false};JS_SetInterruptHandler(runtime.get(),interrupt,&state);
    Context context{JS_NewContext(runtime.get())};if(!context)return failure(EvaluationStatus::budget_exceeded,DiagnosticCode::memory_budget_exceeded,"QuickJS context exceeded the memory budget.");
    auto global=JS_GetGlobalObject(context.get());for(const auto& binding:validated.effective_bindings){if(JS_DefinePropertyValueStr(context.get(),global,binding.first.c_str(),to_js(context.get(),binding.second),JS_PROP_ENUMERABLE)<0){JS_FreeValue(context.get(),global);return failure(EvaluationStatus::budget_exceeded,DiagnosticCode::memory_budget_exceeded,"QuickJS binding allocation exceeded the memory budget.");}}JS_FreeValue(context.get(),global);
    const auto source="("+request.program.source+"\n)";
    auto compiled=JS_Eval(context.get(),source.data(),source.size(),"<phoenix-expression>",JS_EVAL_TYPE_GLOBAL|JS_EVAL_FLAG_COMPILE_ONLY);
    if(JS_IsException(compiled)){if(state.cancelled||state.exhausted)return interrupted(state);const auto message=exception(context.get());return failure(EvaluationStatus::failed,DiagnosticCode::compile_error,message);}
    auto result=JS_EvalFunction(context.get(),compiled);
    if(JS_IsException(result)){if(state.cancelled||state.exhausted)return interrupted(state);const auto message=exception(context.get());if(message.find("out of memory")!=std::string::npos)return failure(EvaluationStatus::budget_exceeded,DiagnosticCode::memory_budget_exceeded,message);return failure(EvaluationStatus::failed,DiagnosticCode::evaluation_error,message);}
    if(JS_IsUndefined(result)){JS_FreeValue(context.get(),result);return failure(EvaluationStatus::failed,DiagnosticCode::evaluation_error,"Expression evaluated to undefined.");}
    EvaluationResult output;output.status=EvaluationStatus::completed;
    if(JS_IsBool(result))output.value=Value{JS_ToBool(context.get(),result)!=0};
    else if(JS_VALUE_GET_TAG(result)==JS_TAG_INT){std::int64_t value=0;JS_ToInt64(context.get(),&value,result);output.value=Value{value};}
    else if(JS_IsNumber(result)){double value=0;JS_ToFloat64(context.get(),&value,result);output.value=Value{value};}
    else if(JS_IsString(result))output.value=Value{text(context.get(),result)};
    else {JS_FreeValue(context.get(),result);return failure(EvaluationStatus::rejected,DiagnosticCode::unsupported_result,"Expression result is not a supported scalar value.");}
    JS_FreeValue(context.get(),result);return output;
}

ScriptResult QuickJsEngine::execute_script(const ScriptRequest& request,
    GeometryScriptHost& transaction,const CancellationToken* cancellation)const
{
    if(request.program.source.empty())return script_failure(EvaluationStatus::rejected,DiagnosticCode::empty_source,"Script source is empty.");
    if(cancellation&&cancellation->cancelled())return script_failure(EvaluationStatus::cancelled,DiagnosticCode::cancelled,"Script execution was cancelled.");
    std::set<std::string> library_ids;
    for(const auto& library:request.libraries){if(library.id.empty()||library.source.empty())return script_failure(EvaluationStatus::rejected,DiagnosticCode::compile_error,"Script library id and source must be non-empty.");if(!library_ids.insert(library.id).second)return script_failure(EvaluationStatus::rejected,DiagnosticCode::compile_error,"Duplicate script library id: "+library.id);}
    EvaluationRequest binding_request;binding_request.program.source="binding validation";binding_request.local_bindings=request.bindings;const auto validated=validate_request(binding_request);if(!validated.success())return {EvaluationStatus::rejected,{},validated.diagnostics,{}};
    Runtime runtime{JS_NewRuntime()};if(!runtime)return script_failure(EvaluationStatus::failed,DiagnosticCode::engine_unavailable,"QuickJS runtime allocation failed.");
    JS_SetMemoryLimit(runtime.get(),static_cast<std::size_t>(request.limits.memory_bytes));
    const auto stack=std::max<std::uint64_t>(64U<<10U,std::min<std::uint64_t>(request.limits.memory_bytes/4,static_cast<std::uint64_t>(request.limits.recursion_depth)*(16U<<10U)));JS_SetMaxStackSize(runtime.get(),static_cast<std::size_t>(stack));
    InterruptState state{cancellation,std::max<std::uint64_t>(1,request.limits.instruction_budget/1024),false,false};JS_SetInterruptHandler(runtime.get(),interrupt,&state);
    Context context{JS_NewContext(runtime.get())};if(!context)return script_failure(EvaluationStatus::budget_exceeded,DiagnosticCode::memory_budget_exceeded,"QuickJS context exceeded the memory budget.");
    ScriptContextState context_state{&transaction,{}};JS_SetContextOpaque(context.get(),&context_state);
    auto td=JS_NewObject(context.get()),vars=JS_NewObject(context.get()),labels=JS_NewObject(context.get()),inputs=JS_NewObject(context.get());
    bool object_error=JS_IsException(td)||JS_IsException(vars)||JS_IsException(labels)||JS_IsException(inputs);
    for(const auto& binding:validated.effective_bindings)object_error=object_error||!set(context.get(),vars,binding.first,to_js(context.get(),binding.second));
    for(const auto& label:request.labels)object_error=object_error||!set(context.get(),labels,label.first,JS_NewInt64(context.get(),label.second.value()));
    JSValue first_input=JS_UNDEFINED;bool have_first=false;
    for(const auto& port:transaction.input_ports()){
        auto input=JS_NewObject(context.get()),mesh=JS_NewObject(context.get());
        object_error=object_error||JS_IsException(input)||JS_IsException(mesh);
        object_error=object_error||!set(context.get(),mesh,"size_of_vertices",JS_NewInt64(context.get(),static_cast<std::int64_t>(transaction.vertex_count(port))));
        object_error=object_error||!set(context.get(),mesh,"size_of_facets",JS_NewInt64(context.get(),static_cast<std::int64_t>(transaction.face_count(port))));
        JS_FreezeObject(context.get(),mesh);object_error=object_error||!set(context.get(),input,"mesh",mesh);
        if(const auto kind=transaction.input_selection_kind(port)){const auto tokens=transaction.input_selection_handles(port);const char* token_kind=*kind==ScriptOutputKind::vertices?"vertices":*kind==ScriptOutputKind::halfedges?"halfedges":"faces";const char* property=*kind==ScriptOutputKind::vertices?"vertices3":*kind==ScriptOutputKind::halfedges?"edges3":"faces3";auto selected=JS_NewArray(context.get());for(std::size_t i=0;i<tokens.size();++i)JS_SetPropertyUint32(context.get(),selected,static_cast<std::uint32_t>(i),handle_object(context.get(),token_kind,tokens[i]));JS_FreezeObject(context.get(),selected);object_error=object_error||!set(context.get(),input,property,selected);}
        JS_FreezeObject(context.get(),input);
        if(!have_first){first_input=JS_DupValue(context.get(),input);have_first=true;}
        object_error=object_error||!set(context.get(),inputs,port,input);
    }
    JS_FreezeObject(context.get(),vars);JS_FreezeObject(context.get(),labels);JS_FreezeObject(context.get(),inputs);
    object_error=object_error||!set(context.get(),td,"vars",vars)||!set(context.get(),td,"labels",labels)||!set(context.get(),td,"inputs",inputs);
    if(have_first)object_error=object_error||!set(context.get(),td,"input",first_input);
    object_error=object_error||!add_function(context.get(),td,"createGeometry",native_create_geometry,1)
        ||!add_function(context.get(),td,"cloneGeometry",native_clone_geometry,2)
        ||!add_function(context.get(),td,"vertexCount",native_vertex_count,1)
        ||!add_function(context.get(),td,"faceCount",native_face_count,1)
        ||!add_function(context.get(),td,"vertex",native_vertex,2)
        ||!add_function(context.get(),td,"face",native_face,2)
        ||!add_function(context.get(),td,"setVertex",native_set_vertex,5)
        ||!add_function(context.get(),td,"addVertex",native_add_vertex,4)
        ||!add_function(context.get(),td,"addFace",native_add_face,4)
        ||!add_function(context.get(),td,"setFaceLabel",native_set_face_label,3)
        ||!add_function(context.get(),td,"setDirectedEdgeLabel",native_set_edge_label,4)
        ||!add_function(context.get(),td,"removeFace",native_remove_face,2)
        ||!add_function(context.get(),td,"elements",native_elements,2)
        ||!add_function(context.get(),td,"inspectGeometry",native_inspect_geometry,1)
        ||!add_function(context.get(),td,"inspect",native_inspect_element,1)
        ||!add_function(context.get(),td,"splitEdge",native_split_edge,1)
        ||!add_function(context.get(),td,"splitFacet",native_split_facet,2)
        ||!add_function(context.get(),td,"joinFacet",native_join_facet,1)
        ||!add_function(context.get(),td,"flipEdge",native_flip_edge,1)
        ||!add_function(context.get(),td,"makeHole",native_make_hole,1)
        ||!add_function(context.get(),td,"fillHole",native_fill_hole,1)
        ||!add_function(context.get(),td,"splitVertex",native_split_vertex,2)
        ||!add_function(context.get(),td,"joinVertex",native_join_vertex,1)
        ||!add_function(context.get(),td,"createCenterVertex",native_create_center,1)
        ||!add_function(context.get(),td,"eraseCenterVertex",native_erase_center,1)
        ||!add_function(context.get(),td,"eraseConnectedComponent",native_erase_component,1)
        ||!add_function(context.get(),td,"keepLargestConnectedComponents",native_keep_components,2)
        ||!add_function(context.get(),td,"clear",native_clear,1)
        ||!add_function(context.get(),td,"insideOut",native_inside_out,1)
        ||!add_function(context.get(),td,"normalizeBorder",native_normalize_border,1)
        ||!add_function(context.get(),td,"addVertexAndFacetToBorder",native_add_vertex_border,2)
        ||!add_function(context.get(),td,"addFacetToBorder",native_add_facet_border,2)
        ||!add_function(context.get(),td,"log",native_log,1);
    JS_FreezeObject(context.get(),td);
    auto transform_factories=JS_NewObject(context.get());object_error=object_error
        ||!add_function(context.get(),transform_factories,"identity",native_identity,0)
        ||!add_function(context.get(),transform_factories,"translation",native_translation,1)
        ||!add_function(context.get(),transform_factories,"scaling",native_scaling,3)
        ||!add_function(context.get(),transform_factories,"rotation",native_rotation,2);JS_FreezeObject(context.get(),transform_factories);
    auto constants=JS_NewObject(context.get());set(context.get(),constants,"negative_side",JS_NewInt32(context.get(),-1));set(context.get(),constants,"boundary",JS_NewInt32(context.get(),0));set(context.get(),constants,"positive_side",JS_NewInt32(context.get(),1));set(context.get(),constants,"clockwise",JS_NewInt32(context.get(),-1));set(context.get(),constants,"collinear",JS_NewInt32(context.get(),0));set(context.get(),constants,"counterclockwise",JS_NewInt32(context.get(),1));JS_FreezeObject(context.get(),constants);
    auto global=JS_GetGlobalObject(context.get());object_error=object_error||!set(context.get(),global,"td",td)
        ||!set(context.get(),global,"transforms",transform_factories)
        ||!set(context.get(),global,"constants",constants)
        ||!add_function(context.get(),global,"point3",native_point3,3)
        ||!add_function(context.get(),global,"vec3",native_vec3,3)
        ||!add_function(context.get(),global,"dir3",native_dir3,3)
        ||!add_function(context.get(),global,"segment3",native_segment3,2)
        ||!add_function(context.get(),global,"line3",native_line3,2)
        ||!add_function(context.get(),global,"plane3",native_plane3,4)
        ||!add_function(context.get(),global,"ray3",native_ray3,2)
        ||!add_function(context.get(),global,"triangle3",native_triangle3,3)
        ||!add_function(context.get(),global,"transform3",native_transform3,1)
        ||!add_function(context.get(),global,"build_mesh",native_build_mesh,1)
        ||!add_function(context.get(),global,"normal",native_normal,3)
        ||!add_function(context.get(),global,"intersection",native_intersection,2)
        ||!add_function(context.get(),global,"equals",native_equals,2);
    auto math=JS_GetPropertyStr(context.get(),global,"Math");for(const char* name:{"abs","round","pow","sqrt","ceil","floor","sin","cos","tan","sign"})object_error=object_error||!set(context.get(),global,name,JS_GetPropertyStr(context.get(),math,name));object_error=object_error||!set(context.get(),global,"PI",JS_GetPropertyStr(context.get(),math,"PI"));JS_FreeValue(context.get(),math);JS_FreeValue(context.get(),global);
    if(object_error)return script_failure(EvaluationStatus::budget_exceeded,DiagnosticCode::memory_budget_exceeded,"QuickJS host binding allocation exceeded the memory budget.");
    for(const auto& library:request.libraries){auto value=JS_Eval(context.get(),library.source.data(),library.source.size(),library.id.c_str(),JS_EVAL_TYPE_GLOBAL);if(JS_IsException(value)){if(state.cancelled||state.exhausted)return script_interrupted(state);const auto message=exception(context.get());return script_failure(EvaluationStatus::failed,DiagnosticCode::compile_error,"Library "+library.id+": "+message);}JS_FreeValue(context.get(),value);}
    const auto source="(function main(){\n"+request.program.source+"\n})()";auto result=JS_Eval(context.get(),source.data(),source.size(),"<phoenix-script>",JS_EVAL_TYPE_GLOBAL);
    if(JS_IsException(result)){if(state.cancelled||state.exhausted)return script_interrupted(state);const auto message=exception(context.get());if(message.find("out of memory")!=std::string::npos)return script_failure(EvaluationStatus::budget_exceeded,DiagnosticCode::memory_budget_exceeded,message);return script_failure(EvaluationStatus::failed,DiagnosticCode::evaluation_error,message);}
    if(!JS_IsObject(result)){JS_FreeValue(context.get(),result);return script_failure(EvaluationStatus::rejected,DiagnosticCode::unsupported_result,"Script main must return a named-output object.");}
    JSPropertyEnum* properties=nullptr;std::uint32_t count=0;if(JS_GetOwnPropertyNames(context.get(),&properties,&count,result,JS_GPN_STRING_MASK|JS_GPN_ENUM_ONLY)<0){JS_FreeValue(context.get(),result);return script_failure(EvaluationStatus::failed,DiagnosticCode::evaluation_error,exception(context.get()));}
    ScriptResult output;output.status=EvaluationStatus::completed;
    for(std::uint32_t i=0;i<count;++i){const char* raw=JS_AtomToCString(context.get(),properties[i].atom);const std::string port=raw?raw:"";if(raw)JS_FreeCString(context.get(),raw);auto value=JS_GetProperty(context.get(),result,properties[i].atom);const auto converted=scalar(context.get(),value);if(converted)output.outputs.push_back({port,ScriptOutputKind::scalar,*converted,0,{}});else if(const auto handle=decoded_handle(context.get(),value);handle&&handle->first=="geometry")output.outputs.push_back({port,ScriptOutputKind::geometry,{},handle->second,{}});else if(JS_IsArray(value)){std::int64_t length=0;JS_GetLength(context.get(),value,&length);if(length<=0){JS_FreeValue(context.get(),value);JS_FreePropertyEnum(context.get(),properties,count);JS_FreeValue(context.get(),result);return script_failure(EvaluationStatus::rejected,DiagnosticCode::unsupported_result,"Empty element output has no type: "+port);}std::string kind;std::vector<std::uint64_t> tokens;for(std::int64_t index=0;index<length;++index){auto item=JS_GetPropertyUint32(context.get(),value,static_cast<std::uint32_t>(index));const auto decoded=decoded_handle(context.get(),item);JS_FreeValue(context.get(),item);if(!decoded||(index&&decoded->first!=kind)){tokens.clear();break;}kind=decoded->first;tokens.push_back(decoded->second);}const auto output_kind=kind=="vertices"?ScriptOutputKind::vertices:kind=="halfedges"?ScriptOutputKind::halfedges:kind=="faces"?ScriptOutputKind::faces:ScriptOutputKind::scalar;if(tokens.empty()||output_kind==ScriptOutputKind::scalar){JS_FreeValue(context.get(),value);JS_FreePropertyEnum(context.get(),properties,count);JS_FreeValue(context.get(),result);return script_failure(EvaluationStatus::rejected,DiagnosticCode::unsupported_result,"Invalid element output: "+port);}output.outputs.push_back({port,output_kind,{},0,std::move(tokens)});}else{JS_FreeValue(context.get(),value);JS_FreePropertyEnum(context.get(),properties,count);JS_FreeValue(context.get(),result);return script_failure(EvaluationStatus::rejected,DiagnosticCode::unsupported_result,"Unsupported script output: "+port);}JS_FreeValue(context.get(),value);}
    JS_FreePropertyEnum(context.get(),properties,count);JS_FreeValue(context.get(),result);output.console_output=std::move(context_state.console);return output;
}
} // namespace phoenix::scripting
