#pragma once

#include "backend/error.h"

enum PARTITION_ERRORS
{
	PARTITION_ERROR_LENGTH_ORIGINAL_ORIGINAL_NOT_IMPLEMENTED = 4000,
	PARTITION_ERROR_NOT_ENOUGH_SPACE_FOR_REPEAT = 4001,
	PARTITION_ERROR_LABELED_MISSING_SEGMENT = 4003,
	PARTITION_ERROR_LABELED_MISSING_LABEL = 4004,
	PARTITION_ERROR_SEGMENT_NOT_FOUND = 4005,
	PARTITION_ERROR_LABEL_NOT_FOUND = 4006,
	PARTITION_ERROR_NO_CUTS = 4007,
	PARTITION_ERROR_MISSING_REPEAT_LENGTH = 4008,
	PARTITION_ERROR_DISTANCE_UNNAMED = 4009,
	PARTITION_ERROR_DISTANCE_MISSING_REFERENCE = 4010,
	PARTITION_ERROR_DISTANCE_MISSING_VALUES = 4011,
	PARTITION_ERROR_DISTANCE_MISSING_PCT_REFERENCE = 4012,
	PARTITION_ERROR_DISTANCE_TO_BASE_NOT_IMPLEMENTED = 4013,
	PARTITION_ERROR_DISTANCE_EXPECTS_CUT = 4014,
	PARTITION_ERROR_DISTANCE_INVALID_CUT_ORDER = 4015,
	PARTITION_ERROR_UNNAMED_FACT = 4016,
	PARTITION_ERROR_MISSING_VALUE = 4017,
	PARTITION_ERROR_MISSING_RANGE = 4018,
	PARTITION_ERROR_MISSING_REFERENCE = 4019,
	PARTITION_ERROR_LENGTH_PCT_IN_BASE = 4020,
	PARTITION_ERROR_NO_MATCHING_SEGMENT = 4021,
	PARTITION_ERROR_INVALID_CUT = 4022,
	PARTITION_ERROR = 4023,
	PARTITION_ERROR_MISSING_VARIABLE = 4024,
	PARTITION_ERROR_TESSELLATOR = 4025,
	PARTITION_ERROR_UNKNOWN_FACT = 4026,
	PARTITION_ERROR_CURVE_OUT_OF_BOUNDS = 4027,
	PARTITION_ERROR_CURVE_COLLISION = 4028,
};

class partition_errors
{
public:
	static solver_error create(PARTITION_ERRORS id);
	static solver_error create(PARTITION_ERRORS id, property_tree& data);
};
#pragma once

