#pragma once

#include "backend/error.h"

enum EXTRUSION_ERRORS
{
	EXTRUSION_ERROR_NO_PROFILE = 3000,
	EXTRUSION_ERROR_COLINEAR = 3001,
	EXTRUSION_ERROR_MIXED_SIGNS = 3002,
	EXTRUSION_ERROR_SHARED = 3003,
	EXTRUSION_ERROR_TIMEOUT = 3004,
	EXTRUSION_ERROR_PLAN_INSERT_EDGE1 = 3005,
	EXTRUSION_ERROR_PLAN_INSERT_EDGE_UNKNOWN = 3006,
	EXTRUSION_ERROR_EDGE_CASE = 3007,
};

class extrusion_errors
{
public:
	static solver_error create(EXTRUSION_ERRORS id);
};

